language: rust
sudo: false
script:
- cargo test
- cargo doc --no-deps -p c-ares-sys
- cargo doc --no-deps -p c-ares
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libc-ares-dev
