language: rust
sudo: false
script:
- cargo test --features "old-cares"
- cargo doc --no-deps -p c-ares
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libc-ares-dev
branches:
  only:
    master
install:
- pip install ghp-import --user $USER
after_success: |
  [ $TRAVIS_PULL_REQUEST = false ] && bash ./publish-docs.sh
